### ISSUE TITLE
結巴在部署到 heroku 的時候會有問題

### ISSUE THREAD

**Issue by chnbohwr** [bbandydd/ActivityBot#20]
如題，話說 我昨天想在 aws lambda 放入結巴的 function 但是也是會出現這個問題，估計是heroku 可能不能夠支援結巴中文斷詞 .....

可能要考慮把結巴拆掉.........傷心 😢 

```
2017-02-18T08:48:29.305197+00:00 app[web.1]: 
2017-02-18T08:48:29.305218+00:00 app[web.1]: > ActivityBot@1.0.0 start /app
2017-02-18T08:48:29.305225+00:00 app[web.1]: > babel-node ./src/serverIndex.js --watch
2017-02-18T08:48:29.305225+00:00 app[web.1]: 
2017-02-18T08:48:34.421812+00:00 app[web.1]: module.js:471
2017-02-18T08:48:34.421825+00:00 app[web.1]:     throw err;
2017-02-18T08:48:34.421826+00:00 app[web.1]:     ^
2017-02-18T08:48:34.421827+00:00 app[web.1]: 
2017-02-18T08:48:34.421828+00:00 app[web.1]: Error: Cannot find module './build/Release/nodejieba.node'
2017-02-18T08:48:34.421829+00:00 app[web.1]:     at Function.Module._resolveFilename (module.js:469:15)
2017-02-18T08:48:34.421830+00:00 app[web.1]:     at Function.Module._load (module.js:417:25)
2017-02-18T08:48:34.421830+00:00 app[web.1]:     at Module.require (module.js:497:17)
2017-02-18T08:48:34.421831+00:00 app[web.1]:     at require (internal/module.js:20:19)
2017-02-18T08:48:34.421832+00:00 app[web.1]:     at Object.<anonymous> (/app/node_modules/nodejieba/index.js:1:17)
2017-02-18T08:48:34.421832+00:00 app[web.1]:     at Module._compile (module.js:570:32)
2017-02-18T08:48:34.421833+00:00 app[web.1]:     at Module._extensions..js (module.js:579:10)
2017-02-18T08:48:34.421834+00:00 app[web.1]:     at Object.require.extensions.(anonymous function) [as .js] (/app/node_modules/babel-register/lib/node.js:152:7)
2017-02-18T08:48:34.421834+00:00 app[web.1]:     at Module.load (module.js:487:32)
2017-02-18T08:48:34.421835+00:00 app[web.1]:     at tryModuleLoad (module.js:446:12)
2017-02-18T08:48:34.421836+00:00 app[web.1]:     at Function.Module._load (module.js:438:3)
2017-02-18T08:48:34.421836+00:00 app[web.1]:     at Module.require (module.js:497:17)
2017-02-18T08:48:34.421837+00:00 app[web.1]:     at require (internal/module.js:20:19)
2017-02-18T08:48:34.421837+00:00 app[web.1]:     at Object.<anonymous> (/app/src/modules/None.js:1:15)
2017-02-18T08:48:34.421838+00:00 app[web.1]:     at Module._compile (module.js:570:32)
2017-02-18T08:48:34.421839+00:00 app[web.1]:     at loader (/app/node_modules/babel-register/lib/node.js:144:5)
2017-02-18T08:48:34.421839+00:00 app[web.1]:     at Object.require.extensions.(anonymous function) [as .js] (/app/node_modules/babel-register/lib/node.js:154:7)
2017-02-18T08:48:34.421840+00:00 app[web.1]:     at Module.load (module.js:487:32)
2017-02-18T08:48:34.421841+00:00 app[web.1]:     at tryModuleLoad (module.js:446:12)
2017-02-18T08:48:34.421841+00:00 app[web.1]:     at Function.Module._load (module.js:438:3)
2017-02-18T08:48:34.421842+00:00 app[web.1]:     at Module.require (module.js:497:17)
2017-02-18T08:48:34.421842+00:00 app[web.1]:     at require (internal/module.js:20:19)
2017-02-18T08:48:34.490392+00:00 app[web.1]: 
2017-02-18T08:48:34.502756+00:00 app[web.1]: npm ERR! Linux 3.13.0-105-generic
2017-02-18T08:48:34.503082+00:00 app[web.1]: npm ERR! argv "/app/.heroku/node/bin/node" "/app/.heroku/node/bin/npm" "start"
2017-02-18T08:48:34.503353+00:00 app[web.1]: npm ERR! node v6.9.5
2017-02-18T08:48:34.503575+00:00 app[web.1]: npm ERR! npm  v3.10.10
2017-02-18T08:48:34.503823+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2017-02-18T08:48:34.508047+00:00 app[web.1]: npm ERR! ActivityBot@1.0.0 start: `babel-node ./src/serverIndex.js --watch`
2017-02-18T08:48:34.508222+00:00 app[web.1]: npm ERR! Exit status 1
2017-02-18T08:48:34.508409+00:00 app[web.1]: npm ERR! 
2017-02-18T08:48:34.508577+00:00 app[web.1]: npm ERR! Failed at the ActivityBot@1.0.0 start script 'babel-node ./src/serverIndex.js --watch'.
2017-02-18T08:48:34.508740+00:00 app[web.1]: npm ERR! Make sure you have the latest version of node.js and npm installed.
2017-02-18T08:48:34.508899+00:00 app[web.1]: npm ERR! If you do, this is most likely a problem with the ActivityBot package,
2017-02-18T08:48:34.509062+00:00 app[web.1]: npm ERR! not with npm itself.
2017-02-18T08:48:34.509238+00:00 app[web.1]: npm ERR! Tell the author that this fails on your system:
2017-02-18T08:48:34.509398+00:00 app[web.1]: npm ERR!     babel-node ./src/serverIndex.js --watch
2017-02-18T08:48:34.509565+00:00 app[web.1]: npm ERR! You can get information on how to open an issue for this project with:
2017-02-18T08:48:34.509732+00:00 app[web.1]: npm ERR!     npm bugs ActivityBot
2017-02-18T08:48:34.509888+00:00 app[web.1]: npm ERR! Or if that isn't available, you can get their info via:
2017-02-18T08:48:34.510058+00:00 app[web.1]: npm ERR!     npm owner ls ActivityBot
2017-02-18T08:48:34.510249+00:00 app[web.1]: npm ERR! There is likely additional logging output above.
2017-02-18T08:48:34.558354+00:00 app[web.1]: 
2017-02-18T08:48:34.558681+00:00 app[web.1]: npm ERR! Please include the following file with any support request:
2017-02-18T08:48:34.558817+00:00 app[web.1]: npm ERR!     /app/npm-debug.log
2017-02-18T08:48:34.702061+00:00 heroku[web.1]: State changed from starting to crashed
2017-02-18T08:48:34.684053+00:00 heroku[web.1]: Process exited with status 1
2017-02-18T08:48:34.509398+00:00 app[web.1]: npm ERR!     babel-node ./src/serverIndex.js --watch
2017-02-18T08:48:34.509565+00:00 app[web.1]: npm ERR! You can get information on how to open an issue for this project with:
2017-02-18T08:48:34.509732+00:00 app[web.1]: npm ERR!     npm bugs ActivityBot
2017-02-18T08:48:34.509888+00:00 app[web.1]: npm ERR! Or if that isn't available, you can get their info via:
2017-02-18T08:48:34.510058+00:00 app[web.1]: npm ERR!     npm owner ls ActivityBot
2017-02-18T08:48:34.510249+00:00 app[web.1]: npm ERR! There is likely additional logging output above.
2017-02-18T08:48:34.558354+00:00 app[web.1]: 
2017-02-18T08:48:34.558681+00:00 app[web.1]: npm ERR! Please include the following file with any support request:
2017-02-18T08:48:34.558817+00:00 app[web.1]: npm ERR!     /app/npm-debug.log
2017-02-18T08:48:34.702061+00:00 heroku[web.1]: State changed from starting to crashed
2017-02-18T08:48:34.684053+00:00 heroku[web.1]: Process exited with status 1

```

**Comment by bbandydd** [comment]
http://blog-jfttt.herokuapp.com/blog/2013/11/30/heroku-gae-python/
可以trytry看

**Comment by chnbohwr** [comment]
一開始沒講清楚， 哈哈， 他的錯誤可能出在 npm install 安裝安裝節巴的時候需要使用到 c 編譯器  `node-gyp rebuild` 

那個時候就沒有辦法在 heroku 環境內 build 通過 ，所以後來 code 就會呼叫不到，就是想說要不要先也把結疤拆掉，之後在看看有沒有機會轉移到 lambda python 環境或是其他 heroku python 做成restful api 給我們 call
